services:
  - type: web
    name: mask-dashboard
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python dash_app.py
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true

